services:
  claude-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-proxy
    ports:
      - "3010:3010"
    volumes:
      - ./src:/app/src
      - ./workspace:/workspace
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: "redis:7-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
